on: 
  workflow_run:
    workflows: ["build"]
    types:
      - completed
name: 🚀 Deploy website on build
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: xn513679.ftp.tools
        username: xn513679_sitedeploy
        password: ${{ secrets.FTP_SEC }}
        exclude: |
          **/.git*
          **/.git*/**
          *.scss
